### ISSUE TITLE
Problem with anyhow

### ISSUE THREAD

**Issue by mveljko1978** [Shopify/javy#127]
/home/veljko/.cargo/registry/src/github.com-1ecc6299db9ec823/anyhow-1.0.55/src/error.rs:617:14
    |
617 |         ptr::addr_of!((*unerased.as_ptr())._object) as *mut E,
    |              ^^^^^^^ could not find `addr_of` in `ptr`

**Comment by saulecabrera** [comment]
Could you clarify which problem are you facing exactly?
