### ISSUE TITLE
Using javy to compile and distribute a wasm file

### ISSUE THREAD

**Issue by rawpixel-vincent** [Shopify/javy#128]
I'm using javy in a github actions to publish a wasm file for a library under public domain license.

is it ok to do so?

do I need to credits javy somehow?

thank you

links: 
https://github.com/rawpixel-vincent/obfuscate-mail#web-assembly-binary-wasi-compatible
https://github.com/rawpixel-vincent/obfuscate-mail/actions/runs/3211785785/workflow

**Comment by saulecabrera** [comment]
Javy in licensed under Apache 2.0, so I believe this is fine.
