### ISSUE TITLE
how to execute javy inside of a wasi runtime

### ISSUE THREAD

**Issue by james-lawrence** [Shopify/javy#160]
I noticed the make command generates a javy_core.wasm file. I assume that allows compiling javascript from within a wasi container. are there instructions for this before I spend time reverse engineering how to go about that?

**Comment by saulecabrera** [comment]
The `javy_core` has a main entrypoint, which is [the main function](https://github.com/Shopify/javy/blob/main/crates/core/src/main.rs#L117), if you want to use it on its own, you'd need to find a way to pass in the user's source code and a quickjs context. That function get's exposed as `_start` in the final Wasm. Currently the only way to get the context and source code set is by pre-initializing them through Wizer and through the[ init function](https://github.com/Shopify/javy/blob/main/crates/core/src/main.rs#L15). 

If you just want to try this out, I'd recommend cloning the repo and running `cargo run -p javy index.js -o index.wasm`; where `index.js` is your JavaScript source code. 

And then you can run the resulting WebAssebly in any WASI compliant runtime, for example, using Wasmtime: `echo <your input> | wasmtime index.wasm`

**Comment by saulecabrera** [comment]
This process is clearly documented in the README https://github.com/Shopify/javy#compiling-to-webassembly

**Comment by james-lawrence** [comment]
thanks for the wizer hint; the documentation you linked to is about running the rust binary; not about running the javy as a wasm module.

`cat example.js | wasmtime target/wasm32-wasi/release/javy_core.wasm ` is essentially the command I tried from the start. it panics likely due to that init function you pointed me to.

looks like I was on the correct track and will figure out the rest I guess. =)
