### ISSUE TITLE
Promises non handled

### ISSUE THREAD

**Issue by captHarlock69** [Shopify/javy#194]
I have a javascript code that uses promises (in my specific case a library that parses XML) and runs smoothly when run with quickjs, but when run thrugh javy and then run with wasmtime it does not run. I then tested a small script with just a simple promise that resolves immediatly but the code does not run.
Bottomline: are promises handled ? is there some change I must add to a code with promises to run correctly ?

**Comment by saulecabrera** [comment]
Hey @captHarlock69 Promises are not handled at the moment. We have plans to support them at some point in the near future.
