### ISSUE TITLE
error: failed to run custom build command for `quickjs-wasm-sys v0.1.2

### ISSUE THREAD

**Issue by hitarth-langaliya** [Shopify/javy#232]
When I try to run the make command it returns this error `error: failed to run custom build command for 'quickjs-wasm-sys v0.1.2'`

**Comment by zenghj** [comment]
same problem

mac os 10.14.6

has installed dependencies one by one, one exception is that `softwareupdate --install-rosetta` got  error "softwareupdate: unrecognized option `--install-rosetta'"
