### ISSUE TITLE
How does Javy support Node.js & NPM modules?

### ISSUE THREAD

**Issue by LijieZhang1998** [Shopify/javy#265]
Usually JS script requires other npm modules. Is Javy able to compile them together? I tried to have code `require("firebase-admin/app")` to use firebase sdk in my code but it's not working.

**Comment by jeffcharles** [comment]
> Is Javy able to compile them together?

You need to use `esbuild` or another bundler to combine your JavaScript files into a single JS file.

Javy only includes APIs present in [the ECMAScript 2020 Language specification](https://262.ecma-international.org/11.0/#sec-intro). It does not include support for NodeJS APIs that are not present in that specification. That is, Firebase client support is unlikely to work.

**Comment by LijieZhang1998** [comment]
Got it. Thank you.
