### ISSUE TITLE
Web APIs support

### ISSUE THREAD

**Issue by bytezeroseven** [Shopify/javy#286]
Would be pretty good if this tool can support Web APIs. A js file with all the necessary imports for running the wasm module should be auto-generated. I can't seem to find any js to wasm toolchain that actually supports Web APIs.

**Comment by gc-victor** [comment]
Somehow related to this topic, I have released a JS-Runtime based on quickjs-wasm-rs. While it does not encompass the entire Minimum Common Web Platform API proposal, it does include the implementation of the Fetch API.

https://github.com/gc-victor/js-wasm-workers-runtime
https://common-min-api.proposal.wintercg.org/

**Comment by bytezeroseven** [comment]
@jeffcharles I have a question. I am assuming this tool just embeds a js engine and makes it run our js code. So js code isn't really converted to anything else and remain as it is? I mean if it only embeds a js engine and makes it run our js code, js code can be extracted easily. 
Or is the js code actually converted into bytecode? 

Not related to this, but in the past week, I actually ended up making a system on top of assemblyscript for accessing every web API from the wasm side. Its not yet public though. Below is a screenshot of its syntax.  ![image-44.png](https://user-images.githubusercontent.com/37891945/227750369-ca1448d1-1cb9-4e3a-a66a-1f38914fd790.png)

**Comment by jeffcharles** [comment]
> I am assuming this tool just embeds a js engine and makes it run our js code. So js code isn't really converted to anything else and remain as it is?

We compile the JS source code to QuickJS bytecode as part of the `javy compile ...` invocation and the QuickJS bytecode is stored in one or more data segments in the Wasm module that's produced.

> I mean if it only embeds a js engine and makes it run our js code, js code can be extracted easily.

Agreed. We have a dynamic linking mode that can be activated with the `-d` flag when using `javy compile` and that creates a Wasm module that just contains the QuickJS bytecode and a small number of instructions to invoke functions in a different Wasm module to drive the interpreter. The interpreter Wasm module can be obtained by running `javy emit-provider ...`.

**Comment by jeffcharles** [comment]
I'm going to close this for now as we're not planning on adding Web API support to this project for the time being. I suggest using the `quickjs-wasm-rs` crate directly. It's what Javy uses to execute JS source code in a Rust application that's been compiled to Wasm. You can use the `eval_global` and `wrap_callback` functions on `Context` to add the APIs you would like into the context that the JS code is evaluated inside.
