### ISSUE TITLE
Execute wasm binary file generated by javy in HTML

### ISSUE THREAD

**Issue by aarthi0808** [Shopify/javy#290]
**I have created a webAssembly binary file from simple javascript file by javy.**

**But I am unable to execute this webAssembly binary file in my html file. Kindly suggest me how to proceed.**

**simple javascript file - add.js**

```
export function add(a,b){
	return a + b;
}
```

**Generated wasm file by following command**

```javy compile add.js -o add.wasm```

**Now I am trying to load this wasm file**

```
fetch('add.wasm')
  .then(response => response.arrayBuffer())
  .then(bytes => WebAssembly.instantiate(bytes))
  .then(result => {
    // Call a function in the WebAssembly module
    const add = result.instance.exports.add;
    console.log(add(2, 3.5)); // Output: 5.5
  });
```

**But it throws error like**
```Uncaught (in promise) TypeError: WebAssembly.instantiate(): Imports argument must be present and must be an object```

**Help me if I missed something**

**Comment by saulecabrera** [comment]
There isn't a concrete mechanism to export JS functions to Wasm at the moment, by default, code at the top level will get evaluated. So you could restructure your code a bit to make your example work:

```js
function add(a, b) {
   return a + b;
}

add(1, 2);
```
If you'd like to make your exported functions available in your Wasm, you'd need to assemble a custom runtime with the crates included in this project. I'll note that we have plans to tackle this at some point in the future.

**Comment by aarthi0808** [comment]
@saulecabrera Can you please share demo or guidelines on how to assemble a custom runtime with the crates. Please share some documentation.

**Comment by saulecabrera** [comment]
The process isn't super documented, but the best example is to follow what's done in the `core` crate https://github.com/Shopify/javy/blob/main/crates/core/src/main.rs#L13 and modify that to your needs. Note that the core crates uses all the other crates in this repo.

**Comment by saulecabrera** [comment]
I'm closing this since the main question was already answered, but feel free to continue the discussion here.
