### ISSUE TITLE
How to export functions

### ISSUE THREAD

**Issue by lok0613** [Shopify/javy#302]
if there are multiple functions in a single js file, how can I export those function without spliting my source code into files?
It would be like `wasmtime --invoke my_func index.wasm`

**Comment by jeffcharles** [comment]
Javy does not currently support exporting functions from JavaScript code from the produced Wasm module. So whether it's a single function or multiple functions that you're trying to export from a Wasm module, they won't be exported.

Wasm modules produced by Javy use the WASI command pattern. That is, the Wasm module exports a `_start() -> ()` function that evaluates the JavaScript code provided.
