### ISSUE TITLE
Shopify Functions - M1 Mac Pro Javy UnhandledPromiseRejectionWarning

### ISSUE THREAD

**Issue by ricksnathan** [Shopify/javy#304]
I am currently following the guide [here](https://shopify.dev/docs/apps/checkout/delivery-customizations/getting-started) starting with step 1. Before step 8, I try and run "npm run build" to compile my function (written in JS), but I'm greeted with the following error:

Running javy ...
(node:27385) UnhandledPromiseRejectionWarning: TypeError: resp.headers.get(...).split(...).at is not a function
    at getDesiredVersionNumber (file:///Users/user/Documents/Projects/shop-functions/node_modules/javy-cli/index.js:96:49)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async main (file:///Users/user/Documents/Projects/shop-functions/node_modules/javy-cli/index.js:15:18)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:27385) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)

--------------

Which refers to this function
/**
 * getDesiredVersionNumber returns the version number of the release that
 * should be downloaded and launched. If the FORCE_RELEASE env variable is set,
 * that will be used as the desired version number, if not, we determine the
 * latest release available on GitHub.
 *
 * GitHub has a public Release API, but  rate limits it per IP, so that the
 * CLI can end up breaking. Instead, we use a little trick. You can download
 * artifacts from the latest release by using `latest` as your version number.
 * The server will respond with a 302 redirect to the artifact's URL. That URL
 * contains the actual release version number, which we can extract.
 */
async function getDesiredVersionNumber() {
	if (process.env.FORCE_RELEASE) return process.env.FORCE_RELEASE;
	const resp = await fetch(
		`https://github.com/${REPO}/releases/latest/download/lol`,
		{ redirect: "manual" }
	);
	if (resp.status != 302) {
		throw Error(
			`Could not determine latest release using the GitHub (Status code ${resp.status
			}): ${await resp.text().catch(() => "<No error message>")}`
		);
	}
	return resp.headers.get("location").split("/").at(-2);
}

Just trying to debug and see why this could be happening, and whether or not it's dependent upon my OS as I'm fairly new to this topic. 

Current setup:
Apple M1 Pro, macOS Monterey 12.3.1
NPM: 7.24.2
Node: 14.18.0
App is using a node template, function is in JS

**Comment by jianghong** [comment]
Hi @ricksnathan , I see your version of Node is quite old. Can you try updating to the latest stable version of Node? It's possible this is not the issue but I want to eliminate possibilities.

**Comment by ricksnathan** [comment]
@jianghong This is a good catch, I assumed everything was fine since I was above the min requirements of node on the Shopify docs for functions. I use [n](https://www.npmjs.com/package/n?activeTab=versions) for managing node versions. After swapping to v. 18.16.0, I am now able to successfully build the function, so I appreciate the speedy reply! 👍
