### ISSUE TITLE
javy npm package.json references non-existing dist folder

### ISSUE THREAD

**Issue by rnovacek** [Shopify/javy#350]
Operating system: Fedora 37 (but shouldn't make a difference)
Processor architecture: x64_64
Rust version: 1.69.0
Javy version: 0.6.0 and npm package 0.10.0

## Problem
The [package.json](https://github.com/Shopify/javy/blob/4f7e5a6680eb0ce12fc2d5cc0923edc5d125a505/npm/javy/package.json) file uses files like `./dist/index.js` which doesn't existing in the [npm package](https://www.npmjs.com/package/javy/v/0.1.0?activeTab=code).

![image](https://user-images.githubusercontent.com/618886/236196490-14d35c71-9763-4692-8123-c37386734be0.png)

Because of this I'm not able to use the npm package.

## Error Message and Context

webpack fails with

```
...my-app/node_modules/javy/dist/fs/index.js doesn't exist
```

...

**Comment by jeffcharles** [comment]
I can confirm that version 0.1.0 was published without the `dist` directory. I've published version 0.1.1 which includes the `dist` folder and confirmed a project that uses that new version will build with esbuild (and probably other bundlers too). Sorry about that!
