### ISSUE TITLE
Extract generic components and add support for binding generation

### ISSUE THREAD

**Issue by saulecabrera** [Shopify/javy#73]
**Goal** : Align on the potential avenues to enable Javy's codebase to serve arbitrary use cases.

**The proposed solutions should**

- Keep compatibility with module snapshotting through [Wizer](https://github.com/bytecodealliance/wizer)
- Allow composing JavaScript modules through module linking (more concretely the Component Model)
- Provide an interface to the underlying JavaScript that allows:
   - Allocating and freeing memory, as described in the [Canonical ABI](https://github.com/WebAssembly/interface-types/pull/140/files)
   - Binding generation for Interface Types (á la wit-bindgen)
- Provide a way to configure multiple data serialization mechanisms (i.e. using messagepack instead of relying on interface types)
- Not define platform specific behavior. The solution should focus only on providing the necessary building blocks as dependencies so that consumers can import those building blocks to build custom solutions. 

**Proposed (high level) changes**

1. Publish the quickjs_sys crate as a standalone crate
2. Remove platform specific behavior from the core crate
    - Custom function entrypoints
    - Factor out the messagepack serialization part into its own crate (i.e. `javy_messagepack`)
    - Remove `crate-type = cdylib`, should be a normal lib crate
3. Add the missing `JS_*` interfaces in the core crate that will help in Interface Types binding generation.
4. Introduce a new crate responsible for interface types binding generation (i.e. `javy_bindgen` / `quickjs_bindgen`)

**Usage**

**With interface types**

In a bindgen-based scenario, a rough sketch of the usage would be:

```rs
// In a custom lib.rs

use javy_bindgen::import!("path/imports.wit"); // (1)
use javy_core::Context; // (2)

let import_obj = Context::new_object()?;

imports::bind(&context, &import_obj); // (3)
```

(1) Generate code for imports (defining a wrapper around the host export, lowering parameters, lifting return values). Similar thing will be done for exports.

(2) `javy_bindgen` will depend on `javy_core`; a given consumer could depend directly on `javy_core` or `javy_bindgen` could re-export the API from `javy_core`.  (This is TBD)

(3) The consumer must explicitly call the setup code 

**With a different serialization mechanism**

In a messagepack-based scenario, a rough sketch of usage would be:

```rs

use javy_messagepack::{to_js_value, to_bytes};
use javy_core::Context;

let input = to_js_value(&context, &bytes).unwrap();
let output  = to_bytes(&output_value.unwrap()).unwrap();
```

**Open questions/tradeoffs/thoughts**

- Regarding the CLI: with the proposed changes and approach, the CLI crate becomes irrelevant IMO in the context of reusability, given that each consumer is responsible for creating a project and for putting each of the pieces together depending on each use case, following that line of thought, each consumer/use case will be responsible for providing their own CLI implementation. Thoughts?

- Regarding binding generation for exports/imports: I took Suborbital's base implementation[^1] as a reference, and therefore this proposal operates under the assumption that import and export generation will always be static (at compile time) and always made completely available to the JS source code,  I could see a possibility where the generation should be done in a more dynamic way, in which the consumer specifies a subset of the functionality that they'd like to import, but I'm not sure if: (i) that's a realistic use case (ii) such use case should be considered as part of this proposal (iii) the feasibility of such use case.

- Is there anything else that should be included? Excluded?

[^1]: https://github.com/suborbital/javy/pull/3

**Comment by nickwesselman** [comment]
> each consumer/use case will be responsible for providing their own CLI implementation

Interesting that you say this, because in looking at [napi](https://napi.rs/docs/introduction/getting-started) as a means of distributing javy via npm, it occurred to me that we probably want a JavaScript/Node CLI that calls into javy as a library, rather than a Rust-based CLI.

**Comment by saulecabrera** [comment]
I think we'll revisit this at some point, but for now I'm closing it.
