### ISSUE TITLE
Not able to execute the `make` command for Javy 

### ISSUE THREAD

**Issue by Deepansharora27** [Shopify/javy#94]
Operating System : macOS Catalina (version 10.15.7)

Hi, 
I have installed all the dependencies prior to running the `make` command , but I am getting this error again and again:
![Screenshot 2022-03-21 at 11 16 47 AM](https://user-images.githubusercontent.com/43300955/159210948-6d79e0db-0afe-48c0-9a0d-7ed362d2c410.png)

**Comment by saulecabrera** [comment]
Hi @Deepansharora27 it seems that you're missing WASI-SDK. Did you run `make download-wasi-sdk`? It is specified in the [Build](https://github.com/Shopify/javy#build) section.

**Comment by Deepansharora27** [comment]
Yes I already did it @saulecabrera 
Sorry I should have mentioned it in the issue description 

Despite having it, I am getting this error

**Comment by Deepansharora27** [comment]
Hi @saulecabrera 
I am now able to get away with the Error, and I have successfully installed the `javy` toolchain. 
But When I am trying to generate a WASM Binary out of my JavaScript File, it is throwing the following error: 
![Screenshot from 2022-03-21 23-14-14](https://user-images.githubusercontent.com/43300955/159332799-20624ce4-deb1-43a7-b26f-f0415a78304f.png)

Can you help me with resolving this ?

**Comment by jianghong** [comment]
Hi @Deepansharora27, your javascript needs to define a global object where `Shopify.main` points to your main function. 

See [example](https://github.com/Shopify/javy/blob/main/crates/cli/tests/sample-scripts/identity.js)

**Comment by Deepansharora27** [comment]
Thanks @jianghong for helping out. I made the changes as you advised and I am able to get away with the Error. 

But there is another warning that is popping up. Can you help with rectifying this warning ? 
![Screenshot from 2022-03-22 11-59-43](https://user-images.githubusercontent.com/43300955/159421354-e6df63bb-34dd-4ba2-97ab-9ef47524bb1c.png)

**Comment by jianghong** [comment]
That's simply a warning and should not affect your output wasm working. It's okay to ignore for now

**Comment by Deepansharora27** [comment]
Thanks for the heads up @jianghong 
Also when I am trying to execute it on Wasmtime, I am not able to see the output. 

When I execute 
`wasmtime run index.wasm` , my terminal does nothing and the output is not being shown to me

**Comment by saulecabrera** [comment]
The default implementation expects a messagepack input to be sent trough stdin, that's why it "hangs".

**Comment by Deepansharora27** [comment]
@saulecabrera I have figured it out. But when I am trying to compile the `core` crate with `--features standalone-wasi`, it gives me this error that `error: Package `javy-core v0.1.0 (/home/deepanshu/javy/crates/core)` does not have the feature standalone-wasi`
